name: Build & Push CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Docker build image
      run: docker build -t ${{ secrets.DOCKERHUB_USER }}/shoeshop_fe:v1 .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USER }}/shoeshop_fe:v1

  scan_source_code_CLImate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Scan with CodeClimate
      run: |
        docker run --rm \
        --env CODECLIMATE_CODE="$PWD" \
        --volume "$PWD":/code \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume /tmp/cc:/tmp/cc \
        codeclimate/codeclimate analyze -f html > shoeshop_fe_codeclimate.html

    - name: Upload HTML report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: shoeshop_fe-report
        path: shoeshop_fe_codeclimate.html

        
        
  scan_source_code_Snyk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Install Snyk-to-html
      run: npm install snyk-to-html -g

    - name: snyk auth
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check vulnerabilities
      run: snyk test --json | snyk-to-html -o shoeshop_fe_snyk.html || true
     
    - name: Upload Snyk HTML report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: shoeshop_fe-snyk-report
        path: shoeshop_fe_snyk.html
